#version 430

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba32f, binding = 0) uniform image2D accumImage;

//-- Data --
vec2 resolution = imageSize(accumImage);
uniform vec3 cameraPos;
uniform vec3 cameraFront;
uniform float fov;

uniform uint frameIndex;

// -- Structs --

struct Material {
    vec3 color;
    float smoothness;
    vec4 emission; //rgb + strength
};

struct Ray {
    vec3 origin;
    vec3 direction;
};

struct Collision {
    uint didHit;
    float distance;
    vec3 hitPoint;
    vec3 normal;
    Material material;
};

struct Hit {
    float distance;
    uint triangleIdx;
};

struct Triangle {
    vec3 a;
    uint materialIdx;
    
    vec3 b;
    uint pad0;

    vec3 c;
    uint pad1;
};

struct Sphere {
    vec3 pos;
    float radius;
    Material material;
};

struct BVHNode {
    vec4 min;
    vec4 max;
    uint left;
    uint right;
    uint triangleCount; // 0 = interior, >0 = leaf
    uint pad;
};

// -- SSBOs --

layout(std430, binding = 0) buffer Spheres {
    Sphere spheres[];
};

layout(std430, binding = 1) buffer Materials {
    Material materials[];
};

layout(std430, binding = 2) buffer Triangles {
    Triangle triangles[];
};

layout(std430, binding = 3) buffer BVHNodes {
    BVHNode nodes[];
};

layout(std430, binding = 4) buffer Data {
    uint maxBounce;
    uint numRaysPerPixel;
    uint SSAA;
};

// -- Functions --

Collision raySphere(Ray ray, Sphere s){
    Collision collision;
    collision.didHit = 0;

    vec3 oc = s.pos - ray.origin;

    float closestApproach = dot(oc, ray.direction);
    if(closestApproach < 0) return collision; //sphere behind ray

    float distRay2 = dot(oc, oc) - closestApproach * closestApproach;
    float r2 = s.radius * s.radius;

    if(distRay2 > r2) return collision; //if distance to ray greater to radius, miss

    collision.distance = closestApproach - sqrt(r2 - distRay2); //closest - distance from closest to sphere surface
    collision.didHit = 1;
    collision.hitPoint = ray.origin + ray.direction * collision.distance;
    collision.normal = (collision.hitPoint - s.pos) / s.radius; // cheaper normal
    collision.material = s.material;
    return collision;
}

float rayAABB(vec3 invDir, vec3 minB, vec3 maxB, float maxDist, vec3 origin){
    vec3 t0 = (minB - origin) * invDir;
    vec3 t1 = (maxB - origin) * invDir;

    vec3 tNear = min(t0, t1);
    vec3 tFar = max(t0,t1);

    float tN = max(tNear.x, max(tNear.y, tNear.z));

    // explicitly calculated tF because it isn't used later
    if(min(tFar.x, min(tFar.y, tFar.z)) < max(tN, 0.0) || tN >= maxDist) return 1e30; 
    return tN;
}

// Moller-Trumbore algorithm
// https://en.wikipedia.org/wiki/Moller-Trumbore_intersection_algorithm
// adapted from https://stackoverflow.com/a/42752998
// only called ONCE on the winning triangle in a set
Collision rayTriangle(Ray ray, Triangle tri){
    Collision c;
    c.didHit = 0;

    vec3 edge1 = tri.b.xyz - tri.a.xyz;
    vec3 edge2 = tri.c.xyz - tri.a.xyz;
    vec3 normalVec = cross(edge1, edge2);
    float det = -dot(ray.direction, normalVec);
    if(abs(det) < 0.0f) return c;

    float invDet = 1.0f/det;
    vec3 ao = ray.origin - tri.a.xyz;
    vec3 dao = cross(ao, ray.direction);
    float u = dot(edge2, dao) * invDet;
    if(u < 0.0f || u > 1.0f) return c;

    float v = -dot(edge1, dao) * invDet;
    if(v < 0.0f || u + v > 1.0f) return c;

    float dist = dot(ao, normalVec) * invDet;
    if(dist <= 0.0) return c;

    c.didHit = 1;
    c.hitPoint = ray.origin + ray.direction * dist;
    c.normal = normalize(normalVec);
    c.distance = dist;
    c.material = materials[tri.materialIdx];

    return c;
}

// shortened triangle test
float rayTriangleDist(Ray ray, Triangle tri){
    vec3 edge1 = tri.b.xyz - tri.a.xyz;
    vec3 edge2 = tri.c.xyz - tri.a.xyz;
    vec3 normalVec = cross(edge1, edge2);
    float det = -dot(ray.direction, normalVec);
    if(det == 0.0) return 1e30;

    float invDet = 1.0f / det;
    vec3 ao = ray.origin - tri.a.xyz;
    vec3 dao = cross(ao, ray.direction);
    float u = dot(edge2, dao) * invDet;
    if(u < 0.0 || u > 1.0) return 1e30;

    float v = -dot(edge1, dao) * invDet;
    if(v < 0.0 || u + v > 1.0) return 1e30;

    float dist = dot(ao, normalVec) * invDet;
    return dist > 0.0 ? dist : 1e30;
}

Collision rayBVH(Ray ray){
    Hit bestHit;
    bestHit.distance = 1e30;
    bestHit.triangleIdx = 0xFFFFFFFF;

    vec3 invDir = 1.0f / ray.direction;

    uint stack[64];
    uint stackPtr = 0;
    stack[stackPtr++] = 0;

    while(stackPtr > 0){
        uint idx = stack[--stackPtr];
        BVHNode node = nodes[idx];

        if(node.triangleCount > 0){
            for(uint i = 0; i < node.triangleCount; i++){
                uint triangleIdx = node.left + i;
                float dist = rayTriangleDist(ray, triangles[triangleIdx]);
                if(dist < bestHit.distance){
                    bestHit.distance = dist;
                    bestHit.triangleIdx = triangleIdx;
                }
            }
        }else{
            BVHNode leftNode  = nodes[node.left];
            BVHNode rightNode = nodes[node.right];
            
            float hitLeft  = rayAABB(invDir, leftNode.min.xyz,  leftNode.max.xyz,  bestHit.distance, ray.origin);
            float hitRight = rayAABB(invDir, rightNode.min.xyz, rightNode.max.xyz, bestHit.distance, ray.origin);

            // < 63 ensures room
            if(hitLeft < 1e30 && hitRight < 1e30 && stackPtr < 63){ 
                if(hitLeft < hitRight){ 
                    stack[stackPtr++] = node.right;
                    stack[stackPtr++] = node.left;
                } else {
                    stack[stackPtr++] = node.left;
                    stack[stackPtr++] = node.right;
                }
            }
            else if(hitLeft  < 1e30 && stackPtr < 64) { stack[stackPtr++] = node.left; }
            else if(hitRight < 1e30 && stackPtr < 64) { stack[stackPtr++] = node.right; }

        }
    }

    if(bestHit.triangleIdx != 0xFFFFFFFF)
        return rayTriangle(ray, triangles[bestHit.triangleIdx]);
    
    Collision miss;
    miss.didHit = 0;
    miss.distance = 1e30;
    return miss;
}

Collision calculateRayCollision(Ray ray)
{
    Collision closest;
    closest.didHit = 0;
    closest.distance = 1e30; // very large distance as a default

    for(int i = 0; i < spheres.length(); i++){
        Collision current = raySphere(ray, spheres[i]);

        if(current.didHit == 1 && current.distance < closest.distance)
            closest = current;
    }

    Collision triCollision = rayBVH(ray);
    if(triCollision.didHit == 1 && triCollision.distance < closest.distance)
        closest = triCollision;

    return closest;
}

float randomFloat(inout uint rng){
    rng = rng * 747796405u + 2891336453u;
    uint result = ((rng >> ((rng >> 28u) + 4u)) ^ rng) * 277803737u;
    result = (result >> 22u) ^ result;

    return float(result) / 4294967295.0;
}

vec3 cosineHemisphereDirection(vec3 normal, inout uint rng){
    float u1 = randomFloat(rng);
    float u2 = randomFloat(rng);

    float r = sqrt(u1);
    float theta = 2.0 * 3.1415926 * u2;

    vec3 tangent = normalize(abs(normal.x) > 0.1 ? cross(vec3(0,1,0), normal) : cross(vec3(1,0,0), normal));

    return normalize(
        r * cos(theta) * tangent + 
        r * sin(theta) * cross(normal, tangent) +
        sqrt(1.0 - u1) * normal
    );
}

vec3 ambient(Ray ray){
    // this can be over-complicated later
    return vec3(0);
}

vec3 trace(Ray ray, inout uint rng){
    vec3 incomingLight = vec3(0);
    vec3 rayColor = vec3(1.0f);

    for(int i=0; i <= maxBounce; i++){
        if(max(rayColor.r, max(rayColor.g, rayColor.b)) < 0.0001) break;

        Collision collision = calculateRayCollision(ray);

        if(collision.didHit == 0){
            incomingLight += ambient(ray);
            break;
        }
        ray.origin = collision.hitPoint + collision.normal * 0.0005;

        vec3 diffuseDir = cosineHemisphereDirection(collision.normal, rng);
        vec3 specularDir = reflect(ray.direction, collision.normal);

        ray.direction = mix(diffuseDir, specularDir, collision.material.smoothness);
        incomingLight += collision.material.emission.rgb * collision.material.emission.a * rayColor;

        rayColor *= collision.material.color.rgb;

        //russian roulette
        float p = max(rayColor.r, max(rayColor.g, rayColor.b));
        if (i > 2){
            p = clamp(p, 0.05, 0.95);

            if(randomFloat(rng) > p) break;

            rayColor /= p;
        }
    }

    return incomingLight;
}

uint hash(uint x) {
    x = ((x >> 16) ^ x) * 0x45d9f3b;
    x = ((x >> 16) ^ x) * 0x45d9f3b;
    x = (x >> 16) ^ x;
    return x;
}

void main()
{
    uvec2 pixel = gl_GlobalInvocationID.xy;
    if (pixel.x >= uint(resolution.x) || pixel.y >= uint(resolution.y))
        return;

    uint rng = hash((pixel.y * uint(resolution.x) + pixel.x) ^ hash(frameIndex));

    vec3 forward = normalize(cameraFront);
    vec3 right   = normalize(cross(forward, vec3(0,1,0)));
    vec3 up      = cross(right, forward);

    

    vec3 totalLight = vec3(0);
    for (int i = 0; i < int(numRaysPerPixel); i++) {
        vec2 uv = vec2(0.0);
        vec2 jitter = vec2(0.0);
        if(SSAA == 1)
            jitter = vec2(randomFloat(rng), randomFloat(rng)) - 0.5;

        uv = (vec2(pixel) + 0.5 + jitter) / resolution;
        vec2 screen = uv - 0.5;
        screen.x *= resolution.x / resolution.y;

        Ray ray;
        ray.origin = cameraPos;
        ray.direction = normalize(1.0/tan(radians(fov) * .5) * forward + screen.x * right + screen.y * up); //fov correction

        totalLight += trace(ray, rng);
    }
    totalLight /= numRaysPerPixel;

    if (frameIndex == 0) {
        imageStore(accumImage, ivec2(pixel), vec4(totalLight, 1.0));
        return;
    }

    vec4 prev = imageLoad(accumImage, ivec2(pixel));
    float weight = 1.0 / (frameIndex + 1);

    vec3 color = mix(prev.rgb, totalLight, weight);
    imageStore(accumImage, ivec2(pixel), vec4(color, 1.0));
}
